export const municipalitiesByProvince = {
  "KwaZulu-Natal": [
    "AbaQulusi Local Municipality",
    "Alfred Duma Local Municipality",
    "Big 5 Hlabisa Local Municipality",
    "City of uMhlathuze Local Municipality",
    "Dannhauser Local Municipality",
    "Dr Nkosazana Dlamini Zuma Local Municipality",
    "eDumbe Local Municipality",
    "Emadlangeni Local Municipality",
    "Endumeni Local Municipality",
    "eThekwini Metropolitan Municipality",
    "Greater Kokstad Local Municipality",
    "Impendle Local Municipality",
    "Inkosi Langalibalele Local Municipality",
    "Inkosi Mtubatuba Local Municipality",
    "Jozini Local Municipality",
    "KwaDukuza Local Municipality",
    "Mandeni Local Municipality",
    "Maphumulo Local Municipality",
    "Mkhambathini Local Municipality",
    "Mpofana Local Municipality",
    "Msunduzi Local Municipality",
    "Mthonjaneni Local Municipality",
    "Ndwedwe Local Municipality",
    "Newcastle Local Municipality",
    "Nkandla Local Municipality",
    "Nongoma Local Municipality",
    "Nquthu Local Municipality",
    "Okhahlamba Local Municipality",
    "Ray Nkonyeni Local Municipality",
    "Richmond Local Municipality",
    "Ulundi Local Municipality",
    "Umdoni Local Municipality",
    "uMfolozi Local Municipality",
    "Umhlabuyalingana Local Municipality",
    "uMlalazi Local Municipality",
    "uMngeni Local Municipality",
    "uMshwathi Local Municipality",
    "uMsinga Local Municipality",
    "Umuziwabantu Local Municipality",
    "Umvoti Local Municipality",
    "Umzimkhulu Local Municipality",
    "Umzumbe Local Municipality",
    "uPhongolo Local Municipality"
  ],
};